import {
  warrior,
  hunter,
  deathKnight,
  mage,
  priest,
  monk,
  rogue,
  warlock,
  paladin,
  shaman,
  druid,
  demonHunter,
} from "./playableClasses";

//Horde Races

const orcM = {
  uid: "orcM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Orc",
  gender: {
    name: "Male",
    imgPath: "/assets/gender-icons/gender_male.png",
  },
  imgPath: "/assets/race-icons/orc_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    monk,
    rogue,
    warlock,
    shaman,
    priest,
  ],
};
const orcF = {
  uid: "orcF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Orc",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/orc_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    monk,
    rogue,
    warlock,
    shaman,
    priest,
  ],
};
const undeadM = {
  uid: "undeadM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Undead",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/undead_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    warlock,
  ],
};
const undeadF = {
  uid: "undeadF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Undead",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/undead_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    warlock,
  ],
};
const taurenM = {
  uid: "taurenM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Tauren",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/tauren_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    priest,
    monk,
    shaman,
    paladin,
    druid,
    mage,
    rogue,
  ],
};
const taurenF = {
  uid: "taurenF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Tauren",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/tauren_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    priest,
    monk,
    shaman,
    paladin,
    druid,
    mage,
    rogue,
  ],
};
const trollM = {
  uid: "trollM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Troll",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/troll_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    warlock,
    shaman,
    druid,
  ],
};
const trollF = {
  uid: "trollF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Troll",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/troll_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    warlock,
    shaman,
    druid,
  ],
};
const bloodElfM = {
  uid: "bloodElfM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Blood Elf",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/blood_elf_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    warlock,
    paladin,
    demonHunter,
  ],
};
const bloodElfF = {
  uid: "bloodElfF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Blood Elf",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/blood_elf_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    warlock,
    paladin,
    demonHunter,
  ],
};
const goblinM = {
  uid: "goblinM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Goblin",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/goblin_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    rogue,
    warlock,
    shaman,
  ],
};
const goblinF = {
  uid: "goblinM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Goblin",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/goblin_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    rogue,
    warlock,
    shaman,
  ],
};
const nightborneM = {
  uid: "nightborneM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Nightborne",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/nightborne_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    warlock,
  ],
};
const nightborneF = {
  uid: "nightborneF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Nightborne",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/nightborne_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    warlock,
  ],
};
const highmountainM = {
  uid: "highmountainM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Highmountain Tauren",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/highmountain_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    monk,
    shaman,
    druid,
    mage,
    priest,
    rogue,
  ],
};
const highmountainF = {
  uid: "highmountainF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Highmountain Tauren",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/highmountain_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    monk,
    shaman,
    druid,
    mage,
    priest,
    rogue,
  ],
};
const magharM = {
  uid: "magharM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Mag'har Orc",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/maghar_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    shaman,
  ],
};
const magharF = {
  uid: "magharF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Mag'har Orc",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/maghar_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    shaman,
  ],
};
const zandalariM = {
  uid: "zandalariM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Zandalari Troll",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/zandalari_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    shaman,
    paladin,
    druid,
  ],
};
const zandalariF = {
  uid: "zandalariF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Zandalari Troll",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/zandalari_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    shaman,
    paladin,
    druid,
  ],
};
const vulperaM = {
  uid: "vulperaM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Vulpera",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/vulpera_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    warlock,
    shaman,
  ],
};
const vulperaF = {
  uid: "vulperaF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Vulpera",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/vulpera_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    warlock,
    shaman,
  ],
};
const hPandarenM = {
  uid: "hPandarenM",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Pandaren",
  gender: { name: "Male", imgPath: "/assets/gender-icons/gender_male.png" },
  imgPath: "/assets/race-icons/pandaren_male.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    shaman,
  ],
};

const hPandarenF = {
  uid: "hPandarenF",
  faction: { name: "Horde", imgPath: "/assets/flags/horde.png" },
  raceName: "Pandaren",
  gender: {
    name: "Female",
    imgPath: "/assets/gender-icons/gender_female.png",
  },
  imgPath: "/assets/race-icons/pandaren_female.png",
  availableClasses: [
    warrior,
    hunter,
    deathKnight,
    mage,
    priest,
    monk,
    rogue,
    shaman,
  ],
};

// End of Horde Races
export const hordeMales = [
  orcM,
  undeadM,
  taurenM,
  trollM,
  bloodElfM,
  goblinM,
  nightborneM,
  highmountainM,
  magharM,
  zandalariM,
  vulperaM,
  hPandarenM,
];
export const hordeFemales = [
  orcF,
  undeadF,
  taurenF,
  trollF,
  bloodElfF,
  goblinF,
  nightborneF,
  highmountainF,
  magharF,
  zandalariF,
  vulperaF,
  hPandarenF,
];
