export const selectedCharacterData = {
  name: "Pepi",
  gender: "Male",
  faction: "Alliance",
  race: "Dwarf",
  playerClass: "Shaman",
  uid: "dwarfM",
  xp: { currentXP: 258, requiredXP: 400 },
  level: 1,
  iLevel: 1,
  money: 200,
  workDone: 400,
  workRemaining: 200,
  wpc: 1,
  mpc: 1,
  wps: 20,
  mps: 20,
};
